### ISSUE TITLE
Hangi bilgileri kullanmam gerek ?

### ISSUE THREAD

**Issue by alierdem** [yasinkuyu/omnipay-nestpay#11]
merhaba
$gateway->setUserName("DENIZTEST");
$gateway->setClientId("800100000");
$gateway->setPassword("DENIZTEST123");
bunlar, bankadan aldığımız hangi bilgilere karşılık geliyor acaba ? 
username dediği api kullanıcı adı mı? client ID sanırım işyeri numarası, doğru mudur ?

**Comment by yasinkuyu** [comment]
Bankanın ilettiği bilgileri maskeleyerek yazarsanız yardımcı olurum.
