### ISSUE TITLE
Laravel 5.7 uyumluluğu

### ISSUE THREAD

**Issue by mehmetcanyegen** [yasinkuyu/omnipay-nestpay#13]
Merhaba,
Kütüphaneyi laravel son sürüm olan 5.7 üzerinde kullanmaya çalışıyorum fakat composer'ın verdiği bağımlılık sorununu bir türlü çözemedim. 
Kütüphanenin hangi laravel sürümüyle uyumlu olduğunu söylerseniz veya 5.7 ile kullanmak için bir yol gösterebilirseniz çok sevinirim

**Comment by mehmetcanyegen** [comment]
Benzer soruna uğraşan varsa laravel 5.1 ile uyumlu

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/omnipay-nestpay/issues/14

**Comment by mehmetcanyegen** [comment]
> 
> 
> #14

Yasin bey buradaki uyumsuzluk diğer issuedaki sorunla ilgili değil, ikisi ayrı. Laravelin 5.7 sürümünde sanırım ismi gulp du bir paketle sizin kütüphanedeki çakışıyor. laravel yüksek sürüm yüklemeye zorlarken sizinki düşük sürüm istiyor, fakat problemi çözemediğim için 5.1 kullanarak çözdüm
