### ISSUE TITLE
System based initialization problem. Please try again later.

### ISSUE THREAD

**Issue by mehmetcanyegen** [yasinkuyu/omnipay-nestpay#14]
Dökümantasyondaki gibi bir kullanımda, aşağıdaki parametrelerle bu hatayı alıyorum, neyden kaynaklı olabilir
*Edit: Kullanıcı adı, şifre ve clientid alanlarını burada maskeledim, girdiğim bilgiler doğru
**System based initialization problem. Please try again later.**

```
$gateway = Omnipay::create('NestPay');
$gateway->setBank("akbank");
$gateway->setUserName("*******");
$gateway->setClientId("*******");
$gateway->setPassword("*******");
```

**Comment by mehmetcanyegen** [comment]
exception detaylarına baktığımda bir başka issueda belirtilen aynı hatayı aldığımı görüyorum, fakat bir güncellemede merge yapıp çözüldüğünü belirtmenize rağmen sanırım sorun devam ediyor
`[curl] 7: Failed to connect to www.sanalakpos.com port 80: Operation timed out [url] http://www.sanalakpos.com/servlet/cc5ApiServer`
Issue: #7

**Comment by mehmetcanyegen** [comment]
Sorunu hallettim. Repository içerisinde dediğiniz güncelleme mevcut. $protocol değişkeni **https** değerinde olduğu için sorun çıkmıyor fakat composer ile yüklendiğinde değişken **http** geliyor. vendor klasöründen düzelttim

**Comment by yasinkuyu** [comment]
Evet o sorunu daha önce çözmüştük. Composer paketi güncellenmemiş sanırım.

**Comment by eorhan** [comment]
Ziraat bank test modunda bu hatayı alıyorum şuan.
