### ISSUE TITLE
Ziraat Bankası Hakkında

### ISSUE THREAD

**Issue by egehandulger** [yasinkuyu/omnipay-nestpay#3]
Merhaba,

Öncelikle bu faydalı kütüphane için teşekkürler. Desteklenmesi hedeflenen bankalar arasında Ziraat Bankası bulunmuyor ancak Ziraat Bankası da Nestpay kullanıyor. Acaba sizce bu kürüphaneyi Ziraat Bankası sanal POS için kullanabilir miyiz?

**Comment by yasinkuyu** [comment]
Ziraat Asseco-See (NestPay) altyapısını kullanmaya başladıysa vpos url tanımlamak yeterli. Bankanızdan vpos url bilgisini öğrenirseniz ekleyebilirim.

  'test' => 'https://testvpos.asseco-see.com.tr/fim/api',
        'asseco' => 'https://entegrasyon.asseco-see.com.tr/fim/api',
        'isbank' => 'spos.isbank.com.tr',
        'akbank' => 'www.sanalakpos.com',
        'finansbank' => 'www.fbwebpos.com',
        'denizbank' => 'denizbank.est.com.tr',
        'kuveytturk' => 'kuveytturk.est.com.tr',
        'halkbank' => 'sanalpos.halkbank.com.tr',
        'anadolubank' => 'anadolusanalpos.est.com.tr',
        'hsbc' => 'vpos.advantage.com.tr',
        // Todo
        'ingbank' => 'ingbank.est.com.tr',
        'citibank' => 'citibank.est.com.tr',
        'cardplus' => 'cardplus.est.com.tr'

**Comment by egehandulger** [comment]
Ziraat nestpay kullanmaya başlamış gibi görünüyor. Acaba gerekli olan url https://sanalpos2.ziraatbank.com.tr/ olabilir mi?

**Comment by egehandulger** [comment]
3D için şu bilgilere ulaştım:

Raporlar Arabirimi için
Link: https://entegrasyon.asseco-see.com.tr/ziraat/report/user.login

POST Bilgileri
Link: https://entegrasyon.asseco-see.com.tr/fim/est3Dgate
Model : 3D

Dönen Değerlerin API Server'a Gönderilmesi
Link: https://entegrasyon.asseco-see.com.tr/fim/api

Sanırım gerekli olan url " https://entegrasyon.asseco-see.com.tr/fim/est3Dgate "dir.

**Comment by yasinkuyu** [comment]
Güncellemeyi gerçekleştirdim. API Bilgileriyle kullanmaya başlayabilirsiniz.

...
$gateway->setBank("ziraatbank");
...

**Comment by egehandulger** [comment]
Çok teşekkürler.

**Comment by yasinkuyu** [comment]
Rica ederim.
