### ISSUE TITLE
operation time out

### ISSUE THREAD

**Issue by ateskur** [yasinkuyu/omnipay-nestpay#7]
Hocam merhaba,

curl time out hataıs neden alınır acaba? sunucu https olmasına rağmen http'e bağlanaya çalışıyor sanki.

[curl] 7: Failed to connect to www.sanalakpos.com port 80: Operation timed out [url] http://www.sanalakpos.com/servlet/cc5ApiServer

yardımın için teşekkürler

**Comment by yasinkuyu** [comment]
Tekrar kontrol eder misin? https://github.com/yasinkuyu/omnipay-nestpay/pull/8
